version: 2.1
orbs:
  semantic-dotnet: vectra/orb-semantic-dotnet@1

executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

jobs:
  build:
    executor: dotnet-executor
    steps:
      - run:
          name: Skip if Not a Pull Request
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              echo "Not a pull request. Skipping job."
              circleci-agent step halt
            fi
      - checkout
      - run: dotnet restore
      - run: dotnet build --no-restore -c Release

workflows:
  release:
    jobs:
      - semantic-dotnet/pack:
          solution: SemanticRelease.DotNet.sln
          context: DeploymentKeys
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
      - semantic-dotnet/publish:
          context: DeploymentKeys
          requires:
            - semantic-dotnet/pack
  pr-checks:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
            tags:
              ignore: /.*/