version: 2.1

executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0

jobs:
  build:
    executor: dotnet-executor
    steps:
      - run:
          name: Skip if Not a Pull Request
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              echo "Not a pull request. Skipping job."
              circleci-agent step halt
            fi
      - checkout
      - run: dotnet restore
      - run: dotnet build --no-restore -c Release
  pack:
    executor: dotnet-executor
    steps:
      - checkout:
          path: .
          fetch-depth: 0
      - run: dotnet restore
      - run:
          name: Install Node.js
          command: |
            apt-get update \
            && apt-get install -y ca-certificates curl gnupg \
            && mkdir -p /etc/apt/keyrings \
            && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
                 | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
            && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" \
                 > /etc/apt/sources.list.d/nodesource.list \
            && apt-get update \
            && apt-get install -y nodejs
      - restore_cache:
          keys:
            - node-deps-{{ checksum "SemanticRelease.DotNet.sln" }}
            - node-deps-
      - run: mkdir -p artifacts
      - run: |
          npm install --no-save \
            semantic-release \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/exec \
            @semantic-release/github
      - run: npx semantic-release
      - run: |
          if [ "$(find ./artifacts -type f -name '*.nupkg' | wc -l)" -eq 0 ]; then
            echo "{}" > ./artifacts/release.json
            echo "No packages found - release.json written with empty object."
          else
            echo '{"hasRelease": true}' > ./artifacts/release.json
            echo "Packages found - release.json written with release indicator"
          fi
      - persist_to_workspace:
          root: artifacts
          paths:
            - "*.nupkg"
            - "release.json"
      - save_cache:
          key: node-deps-{{ checksum "SemanticRelease.DotNet.sln" }}
          paths: ~/.npm
  publish:
    executor: dotnet-executor
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: Log Release Summary
          command: |
            if jq -e '.hasRelease' ./artifacts/release.json > /dev/null; then
              echo "Release triggered"
            else
              echo "No release triggered"
              circleci-agent step halt
            fi
      - run:
          name: Validate presence of API Key
          command: 'echo "Key is: ${NugetAuthentication:0:4}****"'
      - run:
          name: Push to NuGet
          command: |
            dotnet nuget push "artifacts/*.nupkg" \
              --source "https://api.nuget.org/v3/index.json" \
              --api-key "$NugetAuthentication" \
              --skip-duplicate

workflows:
  release:
    jobs:
      - pack:
          context: DeploymentKeys
          filters:
            branches:
              only: main
            tags:
              ignore: /.*/
      - publish:
          context: DeploymentKeys
          requires:
            - pack
  pr-checks:
    jobs:
      - build:
          filters:
            branches:
              ignore: main
            tags:
              ignore: /.*/